version: '3.8'

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nanobot_data:/root/.nanobot
    command:
      - gateway
    restart: always
    ports:
      - '18790:18790'
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NANO_CONFIG=${NANO_CONFIG}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  nanobot_data:
